name: Validate Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Validate commits
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        timeout-minutes: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        timeout-minutes: 3

      - name: Install commitlint
        run: |
          bun add -d @commitlint/cli @commitlint/config-conventional
        timeout-minutes: 3

      - name: Validate PR commits
        run: |
          bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        timeout-minutes: 2

      - name: Check PR title
        run: |
          echo "${{ github.event.pull_request.title }}" | bunx commitlint
        timeout-minutes: 1
