name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        timeout-minutes: 3

      - name: Install dependencies
        run: bun install
        timeout-minutes: 5

      - name: Run type checking
        run: bun run typecheck
        timeout-minutes: 3

      - name: Build package
        run: bun run build
        timeout-minutes: 3

      - name: Update version if provided
        if: github.event.inputs.version
        run: |
          cd mcp-server
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "Updated package.json to version ${{ github.event.inputs.version }}"
        timeout-minutes: 1

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        timeout-minutes: 1

      - name: Publish to npm
        run: |
          cd mcp-server
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        timeout-minutes: 5

      - name: Create GitHub release tag (if version was updated)
        if: github.event.inputs.version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mcp-server/package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git tag v${{ github.event.inputs.version }}
          git push origin HEAD --tags
        timeout-minutes: 2
